version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=passwordManager
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
